---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmserver-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 9Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmserver
  template:
    metadata:
      labels:
        app: llmserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
              - key: cpu
                operator: In
                values:
                - rk3588
      containers:
      - name: llmserver
        image: darkautism/llmserver-rs
        securityContext:
          privileged: true
        args: ["thanhtantran/gemma-3-1b-it-rk3588-1.2.0"]
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: data
          mountPath: /data/models
        resources:
          requests:
            memory: 1500Mi
            cpu: 2
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: llmserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: llmserver-service
spec:
  selector:
    app: llmserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8443
  type: NodePort
